const express = require("express");
const router = express.Router();
const UserController = require("../controllers/UserController");
const { Authenticate, Authorize } = require("../middlewares/AuthMiddleware");
router.get("/get-all-users",Authenticate,Authorize('admin'), UserController.getAllUsers);
router.get("/get-user/:id",Authenticate, UserController.getUser);
router.put("/update-user/:id",Authenticate, UserController.updateUser);
router.delete("/delete-user/:id",Authenticate, Authorize('admin'), UserController.deleteUser);
router.delete("/delete-all-users",Authenticate, Authorize('admin'), UserController.deleteManyUsers);
module.exports = router;